# Numpy 是什么？

它的本质就是对，1维，2维，或3维数据的封装，就是一个 matrix. panads 就是基于 Numpy 构建出来的。本章主要介绍：

1. 各种维度数据的创建
2. 对数据的操作

### 数据的创建

In [2]:
import numpy as np
import math

In [21]:
a = np.array([1, 2, 3]) # 1维数据
b = np.array([[1,2,3],[4,5,6]]) # 2维数据
c = np.zeros((2,3,4)) # 3维数据. 2，3，4分别代表各个维度的长度

print(a)
print(a.ndim)
print('各个维度的长度：{}'.format(a.shape))
print('-------')

print(b)
print(b.ndim)
print('各个维度的长度：{}'.format(b.shape))
print('-------')

print(c)
print(c.ndim)
print('各个维度的长度：{}'.format(c.shape))

[1 2 3]
1
各个维度的长度：(3,)
-------
[['1' 'fg' '3']
 ['4' '5' '6']]
2
各个维度的长度：(2, 3)
-------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3
各个维度的长度：(2, 3, 4)


In [25]:
e = np.ones((2,3))
print(e)
print('元素数据类型：{}'.format(e.dtype))

[[1. 1. 1.]
 [1. 1. 1.]]
元素数据类型：float64


In [26]:
# 随机生成2维数据
np.random.rand(2,3)

array([[0.58017947, 0.11807048, 0.91203195],
       [0.98693175, 0.54211695, 0.78260307]])

In [34]:
# 创建1维数据
# 参数1: starting bound
# 参数2: ending bound
# 参数3: 每个数的差值
f = np.arange(10, 50, 2)
print(f)
print('-------')

# 总的元素数量要一致，否则报错。-1 代表让程序自动计算另外一个维度，因为总元素是一定的，给出1个维度的长度，一定能算出另1个维度的长度
print(f.reshape(4, -1))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
-------
[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [41]:
# arange 是生成整数的，这回生成 float
# 参数1: starting bound
# 参数2: ending bound
# 参数3: 生成的数量
print(np.linspace(3, 4, 8))

[3.  3.1 3.3 3.4 3.6 3.7 3.9 4. ]


In [15]:
mask=np.full((2,3),255)
print(mask)

zeros=np.zeros((2,3))
print(zeros)

ones=np.ones((2,3))
print(ones)

[[255 255 255]
 [255 255 255]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


### 数据操作

In [44]:
a = np.array([10,20,30,40])
b = np.array([1, 2, 3,4])

c = a-b
print(c)

d = a*b
print(d)

e = (a - 10) * 2
print(e)

[ 9 18 27 36]
[ 10  40  90 160]
[ 0 20 40 60]


In [3]:
a = np.arange(10, 50, 2).reshape(5, -1)
print(a)
print('-------')
print(a > 30)
print('-------')
print("这叫做 Boolean Indexing：{}".format(a[a>30]))

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]
-------
[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
-------
这叫做 Boolean Indexing：[32 34 36 38 40 42 44 46 48]


In [9]:
print(a)
print(a[0:2, 0].sum())
print(a.max())
print(a.min())
print(a.mean())

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]
28
48
10
29.0


In [19]:
floats = np.linspace(3, 4, 8)
print(floats)
modified_array=floats.astype(np.uint8)
print(modified_array)

[3.         3.14285714 3.28571429 3.42857143 3.57142857 3.71428571
 3.85714286 4.        ]
[3 3 3 3 3 3 3 4]


### 数据的选取

In [31]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print('-------')
print(a[0, 3])
print('-------')
print(a[:2, 1:3])
print('注意：选取的数据仅仅是原始数据的 view，如果改变它，原始数据也会随着改变')
sub_array = a[:2, 1:3]
print(sub_array)
sub_array[0, 0] = 1111
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------
4
-------
[[2 3]
 [6 7]]
注意：选取的数据仅仅是原始数据的 view，如果改变它，原始数据也会随着改变
[[2 3]
 [6 7]]
[[   1 1111    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]


In [40]:
print(a)

one_d_arr = a[:, 0]
print("one-dimensional array: ", one_d_arr)
print("shape && dim：{} && {}".format(one_d_arr.shape, one_d_arr.ndim))

two_d_list = a[:, 0:1]
print("二维的: ", one_d_list)
print("shape && dim：{} && {}".format(two_d_list.shape, two_d_list.ndim))

[[   1 1111    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
one-dimensional array:  [1 5 9]
shape && dim：(3,) && 1
二维的:  [1 5 9]
shape && dim：(3, 1) && 2
